"""
Airflow DAG Generator Module
=============================
Generates Airflow DAGs and Databricks Workflow JSON configs.

SSIS → Airflow mapping:
  SQL Server Agent Job      →  Airflow DAG (scheduled)
  SSIS Catalog Execution    →  DatabricksSubmitRunOperator
  Package Parameters        →  base_parameters / args
  Precedence Constraints    →  >> task dependencies
  Event Handlers (OnError)  →  trigger_rule=ONE_FAILED
  Email Task on Failure     →  EmailOperator
  Agent Job Schedule        →  schedule_interval / cron

Supports both:
  PySpark pipelines  →  notebook_task in DAG
  Java pipelines     →  spark_jar_task in DAG
"""

import json
from datetime import datetime


def _to_pascal_case(snake_str: str) -> str:
    return "".join(word.capitalize() for word in snake_str.split("_"))


class AirflowGenerator:
    """Generates Airflow DAGs and Databricks Workflow configs."""

    TEMPLATES = {
        "dag_pyspark": "Airflow DAG — PySpark notebook task",
        "dag_java": "Airflow DAG — Java JAR submission",
        "databricks_job": "Databricks Workflow JSON",
    }

    @staticmethod
    def list_templates():
        return [
            {"id": k, "name": v}
            for k, v in AirflowGenerator.TEMPLATES.items()
        ]

    def generate_dag(self, language: str, details: dict, environment: str) -> dict:
        """Generate an Airflow DAG file dict."""
        code = self._dag(language, details, environment)
        return {
            "name": f"dag_{details['pipeline_name']}.py",
            "language": "python",
            "content": code,
            "type": "orchestration",
        }

    def generate_databricks_job(self, language: str, details: dict, environment: str) -> dict:
        """Generate a Databricks Workflow JSON file dict."""
        code = self._databricks_job(language, details, environment)
        return {
            "name": f"job_{details['pipeline_name']}.json",
            "language": "json",
            "content": code,
            "type": "orchestration",
        }

    # ── Airflow DAG ────────────────────────────────────────

    def _dag(self, language: str, d: dict, env: str) -> str:
        cls = _to_pascal_case(d["pipeline_name"])

        if language == "pyspark":
            task_config = f'''    notebook_task={{
        "notebook_path": "/Repos/prod/etl-replatform/pyspark_gen/pipelines/{d["pipeline_name"]}",
        "base_parameters": {{"env": "{env}"}},
    }},'''
        else:
            task_config = f'''    spark_jar_task={{
        "main_class_name": "com.etl.pipelines.{cls}",
        "parameters": ["{env}"],
    }},
    libraries=[{{"jar": "dbfs:/jars/etl-replatform-1.0.jar"}}],'''

        return f'''"""
============================================================
Airflow DAG: {d["pipeline_name"]}
============================================================
Generated by ETL Replatform
Converted from: {d["ssis_package"]}
Language:       {language.upper()}
Date:           {datetime.now().strftime("%Y-%m-%d")}
============================================================
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.databricks.operators.databricks import (
    DatabricksSubmitRunOperator,
)
from airflow.operators.email import EmailOperator
from airflow.utils.trigger_rule import TriggerRule


# ── DAG Configuration ────────────────────────────────────

default_args = {{
    "owner": "data-engineering",
    "depends_on_past": False,
    "email": ["data-ops@company.com"],
    "email_on_failure": True,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
}}

dag = DAG(
    dag_id="{d["pipeline_name"]}",
    default_args=default_args,
    description="Converted from {d["ssis_package"]}",
    schedule_interval="0 2 * * *",      # Daily at 2 AM UTC
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["etl", "ssis-decommission", "{language}"],
)


# ── Cluster Config ───────────────────────────────────────

CLUSTER_CONFIG = {{
    "spark_version": "14.3.x-scala2.12",
    "node_type_id": "Standard_DS4_v2",
    "num_workers": 4,
    "spark_conf": {{
        "spark.sql.adaptive.enabled": "true",
        "spark.databricks.delta.optimizeWrite.enabled": "true",
    }},
}}


# ── Tasks ────────────────────────────────────────────────

run_pipeline = DatabricksSubmitRunOperator(
    task_id="run_{d["pipeline_name"]}",
    databricks_conn_id="databricks_default",
    new_cluster=CLUSTER_CONFIG,
{task_config}
    dag=dag,
)

notify_failure = EmailOperator(
    task_id="notify_failure",
    to=["data-ops@company.com"],
    subject="[ALERT] {d["pipeline_name"]} Failed",
    html_content="<h3>Pipeline {d["pipeline_name"]} failed.</h3>"
                 "<p>Check Airflow logs for details.</p>",
    trigger_rule=TriggerRule.ONE_FAILED,
    dag=dag,
)


# ── Dependencies (replaces SSIS Precedence Constraints) ──

run_pipeline >> notify_failure
'''

    # ── Databricks Workflow JSON ───────────────────────────

    def _databricks_job(self, language: str, d: dict, env: str) -> str:
        cls = _to_pascal_case(d["pipeline_name"])

        if language == "pyspark":
            task_spec = {
                "notebook_task": {
                    "notebook_path": f"/Repos/prod/etl-replatform/pyspark_gen/pipelines/{d['pipeline_name']}",
                    "base_parameters": {"env": env},
                }
            }
        else:
            task_spec = {
                "spark_jar_task": {
                    "main_class_name": f"com.etl.pipelines.{cls}",
                    "parameters": [env],
                },
                "libraries": [{"jar": "dbfs:/jars/etl-replatform-1.0.jar"}],
            }

        job_config = {
            "name": d["pipeline_name"],
            "description": f"Converted from {d['ssis_package']} ({language})",
            "schedule": {
                "quartz_cron_expression": "0 0 2 * * ?",
                "timezone_id": "UTC",
            },
            "max_concurrent_runs": 1,
            "timeout_seconds": 7200,
            "email_notifications": {
                "on_failure": ["data-ops@company.com"],
            },
            "tasks": [
                {
                    "task_key": f"run_{d['pipeline_name']}",
                    **task_spec,
                    "new_cluster": {
                        "spark_version": "14.3.x-scala2.12",
                        "node_type_id": "Standard_DS4_v2",
                        "num_workers": 4,
                    },
                    "timeout_seconds": 3600,
                    "max_retries": 2,
                }
            ],
        }

        return json.dumps(job_config, indent=2)
